#
@route = places
@version = v1
###
# @name create_place
POST http://0.0.0.0:3000/api/{{version}}/{{route}} HTTP/1.1
Content-Type: application/json
< ./request-content/one-place.json

###
# @name create_place_too_lengthy
POST http://0.0.0.0:3000/api/{{version}}/{{route}} HTTP/1.1
Content-Type: application/json
< ./request-content/one-place-overLength.json

###
# @name create_place_unsupported_media_type
POST http://0.0.0.0:3000/api/{{version}}/{{route}} HTTP/1.1
Content-Type: user-agent
< ./request-content/one-place-overLength.json


###
# @name create_place_1
POST http://0.0.0.0:3000/api/{{version}}/{{route}} HTTP/1.1
Content-Type: application/json
< ./request-content/one-place-1.json